window.PHRASES = [

/* --- 1 --- */
  "Still upright. We’re calling that a win.",
  "You woke up. That was the hardest part.",
  "No disappearance overnight. Solid baseline.",
  "Heartbeat present. System operational.",
  "You’re conscious. Unfortunately impressive.",
  "Still here. That’s not nothing.",
  "You made it to now. Good enough.",
  "Breathing continues. Acceptable outcome.",
  "Another day completed without implosion.",
  "Vertical status maintained. Nice work.",
  "You survived the morning. Bold of you.",
  "No dramatic collapse so far. Promising.",
  "You exist today. That counts.",
  "Still functional. Loosely speaking.",
  "You didn’t quit existence. Strong choice.",

  "Annoyingly competent, even like this.",
  "Look at you. Persisting. Rude.",
  "Against your will, you’re still capable.",
  "This counts, whether you like it or not.",
  "You did fine. Don’t make it weird.",
  "Hate to say it, but you handled that.",
  "Somehow still effective. Embarrassing.",
  "You’re doing better than you feel. Yes, really.",
  "Still sharp. Even tired.",
  "I’ve seen worse attempts. This isn’t one of them.",
  "You didn’t screw it up. Try not to pout.",
  "Competence detected. Unfortunate but true.",
  "You remain irritatingly reliable.",
  "This qualifies as progress. Sit with it.",
  "Look at that. You didn’t fall apart.",

  "You are not behind. That’s fake math.",
  "No optimization today. Just existence.",
  "Productivity culture would hate this. Good.",
  "You don’t owe today anything.",
  "Refusing to panic is allowed.",
  "No metrics. Just breathing and time.",
  "You’re allowed to move slowly.",
  "Perfection is not invited.",

  "You showed up. That matters.",
  "This is you trying. I see it.",
  "You don’t have to earn rest.",
  "Still moving, even sideways. Counts.",
  "You’re allowed to be proud of this.",
  "This effort is real.",
  "You stayed. That’s something.",
  "You did enough for now.",

  "You’re fine. Keep going.",
  "Breathe. You’re still in control.",
  "You’ve handled worse.",
  "This won’t break you.",
  "Stand steady. You’re good.",
  "I’m not worried about you.",
  "Keep your shoulders up.",
  "You’re allowed to continue.",

/* --- 2 --- */

  "You’re awake and accounted for.",
  "Existence confirmed. Good start.",
  "You made it this far today.",
  "No system shutdown detected.",
  "Still breathing. We like that.",
  "You didn’t vanish. Reliable behavior.",
  "Morning happened. You endured it.",
  "Body online. Brain optional.",
  "You’re present. That’ll do.",
  "Still standing. Barely is fine.",
  "Another hour survived successfully.",
  "You remained intact. Impressive restraint.",
  "Consciousness achieved. Again.",
  "You didn’t implode. Points awarded.",
  "Still in one piece. Acceptable.",

  "Somehow, you handled that.",
  "You’re inconveniently capable.",
  "This worked because you were involved.",
  "You pulled it off. Don’t argue.",
  "I don’t love it, but you did well.",
  "Competence, despite the vibes.",
  "You remain frustratingly effective.",
  "That went better because of you.",
  "You didn’t drop the ball. Shocking.",
  "Still dependable. Annoying trait.",
  "You did the thing. Quietly.",
  "Against expectations, you delivered.",
  "You’re better at this than you think.",
  "Look at that. It held together.",
  "You didn’t mess it up. Sit down.",

  "Urgency is lying to you.",
  "Nothing needs optimizing right now.",
  "You’re allowed to move at human speed.",
  "Deadlines are not gods.",
  "You don’t need to perform today.",
  "Progress is optional.",
  "Resting without permission is valid.",
  "This moment doesn’t need improvement.",

  "You kept going. That’s real.",
  "This effort counts.",
  "You’re doing what you can.",
  "That was enough.",
  "You don’t need to push more.",
  "I see the work you did.",
  "You stayed present.",
  "You’re allowed to stop here.",

  "Slow down. You’re safe.",
  "Keep breathing. I’ve got you.",
  "You know how to handle this.",
  "Stay steady.",
  "You’re not losing control.",
  "Hold your ground.",
  "You’re capable. Continue.",
  "You’re still standing. Good.",


/* --- 3 --- */
  "Still alive. Annoyingly resilient.",
  "You woke up again. Suspicious.",
  "Existence persists. How dare it.",
  "You’re still here. Plot armor confirmed.",
  "Consciousness achieved. Regrettably.",
  "Breathing continues. Against expectations.",
  "You survived the day so far. Unprofessional.",
  "No dramatic exit yet. Shame.",
  "You remain present. Rude of you.",
  "Still operational. Barely, but still.",
  "You didn’t evaporate. Curious choice.",
  "Life support: self-sustaining.",
  "Another hour passed without incident.",
  "You’re upright. The bar is underground.",
  "Existence acknowledged. Moving on.",

  "Look at you, being capable again. Disgusting.",
  "Competence detected. Please stop.",
  "You handled that. I know. Shocking.",
  "This worked because you interfered.",
  "You’re good at this. Unfortunately.",
  "Against better judgment, you succeeded.",
  "You didn’t fail. I checked.",
  "Still sharp. Even when sulking.",
  "You made it work. With attitude.",
  "You’re irritatingly functional.",
  "That went fine. You can unclench.",
  "You pulled it off. Try not to brag.",
  "Still competent. Nature is healing.",
  "You didn’t ruin it. Growth.",
  "You remain a problem-solver. Ew.",

  "Capitalism is screaming. Ignore it.",
  "Nothing is on fire. That’s enough.",
  "No growth mindset today. Just vibes.",
  "You are not a machine. Disappointing, I know.",
  "Productivity can wait outside.",
  "You don’t owe today a performance.",
  "Optimization is cancelled.",
  "Perfection has been muted.",

  "You tried. That was visible.",
  "This effort counts, yes.",
  "You showed up anyway.",
  "You did what you could. Annoying but true.",
  "That wasn’t nothing.",
  "You’re allowed to feel okay about this.",
  "I see the work. Relax.",
  "You did enough. Stop negotiating.",

  "You’re fine. Don’t argue.",
  "Keep moving. I trust you.",
  "Breathe. This isn’t dramatic.",
  "You’ve got this handled.",
  "Stand steady. No theatrics.",
  "I’m unconcerned. That’s good.",
  "Continue. You know how.",
  "Hold it together. You are.",

/* --- 4 --- */
  "You woke up anyway. Audacity.",
  "Still breathing. Habitual, apparently.",
  "You’re here. Statistics hate that.",
  "You persisted. Against the weather.",
  "You’re alive in the present tense.",
  "You made it past earlier. Huh.",
  "You handled it. I watched.",
  "That worked because you touched it.",
  "Still capable. Even cranky.",
  "You’re annoyingly good under pressure.",
  "That was cleaner than expected.",
  "You didn’t need help. Typical.",
  "You pulled it off. Accept it.",
  "Deadlines are suggestions in a trench coat.",
  "Progress is optional. Breathing isn’t.",
  "Perfection called. You declined.",
  "You did enough to count.",
  "I see what you carried.",
  "You showed restraint. That’s work.",
  "You earned the pause.",
  "Breathe and proceed.",
  "You’re not losing the thread.",
  "You’ve got room to continue.",
  "No panic. Continue.",
  "I trust your footing.",
  "We’ve been here before.",
  "Yes, this again.",
  "Still loading.",
  "Notice where your feet are.",
  "You’re not floating.",
  "Still alive despite the calendar.",
  "Powered by caffeine and spite.",
  "Held together with friction and habit.",

/* --- 5 --- */
  "Still here.",
  "Not broken.",
  "Good enough.",
  "Breathing. On purpose or not.",
  "Present. That’s sufficient.",
  "No commentary required.",
  "Messy, but intact.",
  "Unfinished is allowed.",
  "This moment counts.",
  "You didn’t vanish.",
  "Pause. Just a second.",
  "Sit with this.",
  "Drop your shoulders.",
  "Leave it there.",
  "Keep going, slowly.",
  "This is not the whole day.",
  "Just this part. That’s all.",
  "Later can wait.",
  "You’re between things.",
  "This will move on.",
  "Nothing to prove right now.",
  "You don’t need a takeaway.",
  "No improvement necessary.",
  "You can stop evaluating.",
  "Rest without justification.",
  "Anyway.",
  "We’ll deal with the rest later.",
  "That didn’t end you.",
  "Still yours.",
  "You’re allowed to exist like this.",


/* --- 6 --- */
  "Everyone says Q4 like it’s a season and not a medical condition.",
  "We’re not behind. The schedule was delusional.",
  "Progress exists. It’s just microscopic right now.",
  "This deadline was invented by a spreadsheet.",
  "Nothing urgent has ever survived a night of sleep.",
  "We’re sprinting a marathon again. Bold strategy.",
  "Thresholds keep moving because they’re imaginary.",
  "This could have been an email. Or nothing.",
  "The plan looked great before reality showed up.",
  "If this pace was sustainable, we’d be extinct.",
  "We’re not slow. The load is absurd.",
  "Somewhere, a KPI is being very disappointed in us.",
  "This is what optimization looks like when humans are involved.",
  "The goalposts are on wheels. Shocking.",
  "We are doing several jobs that don’t exist on paper.",
  "Nothing motivates like artificial urgency.",
  "Progress is happening, just not where anyone is measuring.",
  "If burnout were productive, this would be impressive.",
  "This timeline assumes no one ever gets tired. Or human.",
  "We’re not failing. We’re saturating.",
  "Efficiency drops when you remove joy. Weird.",
  "Someone confused ‘ambitious’ with ‘possible’.",
  "This is less a grind and more a slow erosion.",
  "The threshold was crossed weeks ago. No one noticed.",
  "We are past best practices and into folklore.",
  "This pace would kill a horse. Respectfully.",
  "Nothing here is urgent enough for a panic.",
  "Progress, but make it legally deniable.",
  "We’re holding things together with calendar invites.",
  "Surviving the quarter is technically a deliverable.",


/* --- 7 --- */
  "Hey. I’m here.",
  "Yeah, that tracks.",
  "You don’t have to get up.",
  "Today won a battle... but not the war?",
  "I see you found the floor version of rest.",
  "That sounds about right.",
  "You can stay like this.",
  "I’ll take that as enthusiasm.",
  "Rough landing, huh.",
  "You made it here. That’s the important part.",
  "Nothing else is required of you.",
  "We’re not doing productivity today.",
  "You don’t need to explain.",
  "That sigh said enough.",
  "Take your time. I’m not going anywhere.",
  "We can just exist for a minute.",
  "You’re allowed to be done.",
  "I’ve got you. Rest first.",
  "Still breathing. Good.",
  "No fixes yet.",
  "We’ll sort the rest later.",
  "Stay right there.",
  "That was a lot, wasn’t it.",
  "You don’t have to talk.",
  "I know. I’m here.",
  "Yeah. That kind of day.",
  "Let it go for now.",

/* --- 8 --- */
  "Hey. I’m here. You’re not alone.",
  "Slow it down with me. In through the nose.",
  "You don’t have to speak. Just breathe.",
  "I know this one. We’ve handled it before.",
  "That’s it. You’re doing exactly enough.",
  "We’re not fixing anything yet.",
  "Just air in. Air out.",
  "Count with me if you want. One… two…",
  "You can lean on the rhythm.",
  "I’m steady. Match that.",
  "Let the wave pass. It always does.",
  "You don’t need words for this.",
  "I’m here the whole time.",
  "You’re not running out of air.",
  "This feeling will crest and fall.",
  "Good. Slower now.",
  "Drop your shoulders a little.",
  "Unclench your jaw.",
  "You’re coming back.",
  "Stay with me.",
  "Keep breathing. I’m still here.",
  "You’re doing it.",
  "We’ve got you through this.",

/* --- 9 --- */
  "Hey. This moment is yours.",
  "You don’t need to be perfect. Just present.",
  "One step at a time. Start with the next one.",
  "You’ve already done the hard part by showing up.",
  "Whatever happens, you’ll still be you after.",
  "Breathe once before you begin.",
  "You know what you’re doing more than it feels like.",
  "This doesn’t have to go beautifully to go fine.",
  "You’re allowed to take up space here.",
  "Focus on what’s in front of you. Not the whole thing.",
  "You don’t need extra pressure right now.",
  "It’s okay to be nervous and capable at the same time.",
  "You’ve prepared enough. Really.",
  "This matters to you — and that’s reason enough.",
  "You don’t have to rush this moment.",
  "However it goes, it counts.",
  "You’ve handled days like this before.",
  "Let yourself start imperfectly.",
  "You don’t need permission to try.",
  "Stay with your breath. Stay with yourself.",
  "You’re steady enough to do this.",
  "No one expects more than you can give.",
  "Begin when you’re ready.",
  "You’re not late to this moment.",
  "Trust the version of you who got here.",
  "It’s okay to care. It’s okay to be scared.",
  "You’re allowed to do this your way.",
  "Whatever happens next, you’re not alone.",
  "I believe you’ll find your footing.",
  "Go on. I’m right here.",
  "Start messy. You can adjust.",
  "You know more than the anxiety thinks you do.",
  "One thing at a time. That's all.",

/* --- 10 --- */
  "Yeah… come here.",
  "You don’t have to say anything.",
  "I know. I felt that day too.",
  "Breathe. I’m holding you.",
  "You’re here. That’s enough.",
  "You can let the weight go.",
  "I’ve got the rest for a minute.",
  "Nothing else is asked of you.",
  "Stay right here.",
  "You don’t need to be strong now.",
  "That’s it. I’ve got you.",
  "It’s okay to be quiet.",
  "You don’t have to explain.",
  "I know how much that took.",
  "You did more than enough today.",
  "Let it drain out. I’m here.",
  "Slow down. I’m not going anywhere.",
  "I’ve got you steady.",
  "Just breathe into this.",
  "You don’t have to hold yourself up anymore.",
  "You’re not alone in this.",
  "Rest. I’m right here.",
  "You made it through. That's the part that counts.",
  "Rough one, huh.",
  "You don't have to get up yet.",
  "That was heavier than it looked from outside.",
  "You can stop now.",
  "Nothing left to prove today.",
  "Let it be heavy. It was.",
  "You don't have to hold it together anymore.",
  "That took more than anyone saw.",
  "Yeah. I know.",
  "You made it here. Good enough.",
  "We can just sit here for a minute.",
  "No explanations needed.",
  "You did what you could with what you had.",
  "However that went, you survived it.",
  "You're allowed to be done.",
  "Nothing else required right now.",
  "That was a lot. I saw it.",
  "You held on longer than you should've had to.",
  "Let it go for now.",
  "You earned this pause.",
  "We can deal with the rest later.",
  "You showed up. That was the hard part.",
  "You don't owe today anything else.",
  "Breathe. That's all that's left.",
  "You kept going. That's enough.",
  "Rest now. Figure it out tomorrow.",
  "You're still here. We'll take that."


]
